name: "Full checks"

on:
  schedule:
    - cron: '0 10 * * *'
  pull_request:
  push:
    branches:
      - main

jobs:
  full-checks:
    name: "PHP version ${{ matrix.php-version }}"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system:
          - "ubuntu-22.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: "php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Full CI"
        run: "composer all-checks"

